name: ROS 1 CI

on:
  pull_request:
    branches:
      - 'main'
jobs:
  test_environment-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - noetic
        include:
            # Noetic Ninjemys (May 2020 - May 2025)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-noetic-desktop-latest
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
         package-name: graph_rviz_plugin
         target-ros1-distro: ${{ matrix.ros_distribution }}
         vcs-repo-file-url: ""
